# With thanks to https://gist.github.com/weibeld/f136048d0a82aacc063f42e684e3c494
name: build-and-release
on:
  push:
    branches:
      - main
      - generate-changelog-with-each-release
permissions:
  contents: write
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: src
      - name: Install DJGPP
        run: |
          wget -P /tmp https://github.com/andrewwutw/build-djgpp/releases/download/v3.4/djgpp-linux64-gcc1220.tar.bz2
          echo "8464f17017d6ab1b2bb2df4ed82357b5bf692e6e2b7fee37e315638f3d505f00  /tmp/djgpp-linux64-gcc1220.tar.bz2" | shasum -a 256 --check
          tar -xf /tmp/djgpp-linux64-gcc1220.tar.bz2 -C /opt
          rm /tmp/djgpp-linux64-gcc1220.tar.bz2
      - name: "✏️ Generate release changelog"
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE/src
          test -f main.c
          . /opt/djgpp/setenv
          make
          test -f output/sbemu.exe
      - name: Build FreeDOS SBEMU USB image
        run: |
          shellcheck $GITHUB_WORKSPACE/src/scripts/build-release-artifacts.sh
          $GITHUB_WORKSPACE/src/scripts/build-release-artifacts.sh $GITHUB_WORKSPACE/src/output/sbemu.exe $GITHUB_WORKSPACE/
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=UserBuild_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
      - name: Release FreeDOS SBEMU USB image
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ github.workspace }}/SBEMU.zip
            ${{ github.workspace }}/SBEMU-FD13-USB.img.xz
          body_path: ${{ github.workspace }}/CHANGELOG.md
