# With thanks to https://gist.github.com/weibeld/f136048d0a82aacc063f42e684e3c494
name: build-and-release
on: push
permissions:
  contents: write
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: tmp_src
      - name: checkout-in-case-insensitive-fs
        run: |
          dd if=/dev/zero of=/tmp/VirtBlock.img bs=5M count=1
          mkfs.vfat -n FAT_SRC /tmp/VirtBlock.img
          mkdir $GITHUB_WORKSPACE/src
          sudo mount /tmp/VirtBlock.img $GITHUB_WORKSPACE/src -o rw,uid=$(id -u),gid=$(id -g)
          sh -c 'echo "Hello" > $GITHUB_WORKSPACE/src/TeSt.TxT'
          cat $GITHUB_WORKSPACE/src/test.txt
          echo "Test file stored in path $GITHUB_WORKSPACE/src/test.txt"
          mv $GITHUB_WORKSPACE/tmp_src/* $GITHUB_WORKSPACE/src/
          ls -lh
          ls -lh $GITHUB_WORKSPACE/src/test.txt
          ls -lh $GITHUB_WORKSPACE/src/MAIN.C
          ls -lh $GITHUB_WORKSPACE/src/main.c
      - name: Install DJGPP
        run: |
          pushd /opt
          wget https://github.com/andrewwutw/build-djgpp/releases/download/v3.3/djgpp-linux64-gcc1210.tar.bz2
          tar -xf djgpp-linux64-gcc1210.tar.bz2
          rm djgpp-linux64-gcc1210.tar.bz2
          popd
      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE/src
          ls -lh MAIN.C
          ls -lh main.c
          . /opt/djgpp/setenv
          ./build.sh
          ls -lh output/sbemu.exe
      - name: Build FreeDOS SBEMU USB image
        run: |
          cd /tmp
          wget https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/official/FD13-LiteUSB.zip
          wget https://www.freedos.org/download/verify.txt
          grep -q "64a934585087ccd91a18c55e20ee01f5f6762be712eeaa5f456be543778f9f7e  FD13-LiteUSB.zip" verify.txt
          echo "64a934585087ccd91a18c55e20ee01f5f6762be712eeaa5f456be543778f9f7e  FD13-LiteUSB.zip" | shasum -a 256 --check
          unzip FD13-LiteUSB.zip
          rm FD13-LiteUSB.zip
          mkdir /tmp/mnt
          sudo mount FD13LITE.img /tmp/mnt -t vfat -o loop,offset=$((63*512)),rw,uid=$(id -u),gid=$(id -g)
          cp $GITHUB_WORKSPACE/src/output/sbemu.exe /tmp/mnt/
          ls -lh /tmp/mnt
          sudo umount /tmp/mnt
          mv FD13LITE.img SBEMU-FD13-USB.img
          7z a $GITHUB_WORKSPACE/SBEMU-FD13-USB.7z SBEMU-FD13-USB.img -mx9
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release FreeDOS SBEMU USB image
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: $GITHUB_WORKSPACE/SBEMU-FD13-USB.7z
