# With thanks to https://gist.github.com/weibeld/f136048d0a82aacc063f42e684e3c494
name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: test-case-insensitive-fs
        run: |
          uname -r
          dd if=/dev/zero of=/tmp/VirtBlock.img bs=5M count=1
          mkfs.vfat -n FAT_SRC /tmp/VirtBlock.img
          sudo mkdir /mnt/src
          sudo mount /tmp/VirtBlock.img /mnt/src
          sudo touch /mnt/src/TeSt.TxT
          whoami
          sudo sh -c 'echo "Hello" > /mnt/src/TeSt.TxT'
          cat /mnt/src/test.txt
