# With thanks to https://gist.github.com/weibeld/f136048d0a82aacc063f42e684e3c494
name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: mount-case-insensitive-fs
        run: |
          uname -r
          dd if=/dev/zero of=/tmp/VirtBlock.img bs=5M count=1
          mkfs.vfat -n FAT_SRC /tmp/VirtBlock.img
          mkdir $GITHUB_WORKSPACE/src
          sudo mount /tmp/VirtBlock.img $GITHUB_WORKSPACE/src -o rw,uid=$(id -u),gid=$(id -g)
          sh -c 'echo "Hello" > $GITHUB_WORKSPACE/src/TeSt.TxT'
          cat $GITHUB_WORKSPACE/src/test.txt
